### ISSUE TITLE
Exception about incomplete JSON

### ISSUE THREAD

**Issue by jansorg** [applandinc/appmap-intellij-plugin#382]
Most likely caused by invalid JSON on disk, but it's unclear how it was created like this.

```
2023-08-30 13:33:10,401 [432472432]   WARN - #appland.webviews.appMap.AppMapFileEditor - invalid AppMap json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 663519 path $.classMap[0].children[0].children[3].children[1].children[0].children[27].location
	at com.google.gson.Gson.fromJson(Gson.java:1241)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at appland.webviews.appMap.AppMapFileEditor.createInitData(AppMapFileEditor.java:85)
	at appland.webviews.appMap.AppMapFileEditor.createInitData(AppMapFileEditor.java:52)
	at appland.webviews.WebviewEditor$1.run(WebviewEditor.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 663519 path $.classMap[0].children[0].children[3].children[1].children[0].children[27].location
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1044)
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:798)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:783)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 26 more
```

**Comment by kgilpin** [comment]
Agents should be streaming JSON output to a temp file, then swapping atomically into place to avoid errors like this. @apotterri do you have thoughts on this? Maybe this has since been fixed in the Java agent?

**Comment by apotterri** [comment]
The Java agent does stream to a temp file, then swap atomically. @kgilpin, you originally implemented that, a lot more than 4 months ago.

One way I can think of that this problem could happen would be for the IntelliJ extension to be trying to parse one of those temp file.

@jansorg, if we want to try to track this down, it would be good for the extension to include the full path of the file in the error message. Also, as of 1.26.0, the agent will create log files by default. Including relevant logs in any future updates to the issue could be helpful.

**Comment by kgilpin** [comment]
To make any further progress on this, we would need to know the file name being parsed.
